### ISSUE TITLE
Release an APK

### ISSUE THREAD

**Issue by amitness** [Muneefm/Mi-band-count-down-timer#1]
Please send me the apk for this app. Seems cool.

**Comment by Muneefm** [comment]
There is still some last work left.  will publish the apk to playstore soon.  will let u know once done.

**Comment by amitness** [comment]
Sure. If you're looking for a beta user, do please send me an APK right now. Can't wait to try it out :smile:

**Comment by Muneefm** [comment]
Published the apk in store.   sorry for being late.  
 https://play.google.com/store/apps/details?id=mnf.android.mibandtimer
